version: '2'

services:
    php-apache:
        build: .docker/apache
        container_name: php-apache
        ports :
           - "8001:80"
        volumes:
            - ${WORKSPACE_APP_PATH}:/var/www/workspace
        links:
            - db

    db:
        image: mysql
        ports:
            - "3307:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:4.7.3-1
        container_name: phpmyadmin
        environment:
            PMA_ARBITRARY: 1
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        ports:
            - "8081:80"
        links:
            - db

